# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on:
  push:
    branches:
      - master

env:
  OTP_VERSION: '23.3.4.18'
  # OTP_VERSION: '24.3.4.1'
  ELIXIR_VERSION: '1.13.4'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: 4.1.8
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: gnosischain/blockscout
      
      # - name: Install Rust
      #   uses: actions-rs/toolchain@v1
      #   with:
      #       toolchain: 1.62.0
      #       override: true
      
      # - name: Install `rust-src` Rustup Component
      #   run: rustup component add rust-src
      
      # - name: Run `cargo check`
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: check

      # - name: Run `cargo metadata`
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: metadata
        
      - id: commit
        uses: pr-mpt/actions-commit-hash@v2

      - name: Build & Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          cache-from: type=registry,ref=gnosischain/blockscout:buildcache
          cache-to: type=registry,ref=gnosischain/blockscout:buildcache,mode=max
          tags: gnosischain/blockscout:latest, gnosischain/blockscout:${{ steps.commit.outputs.short }}
          platforms: |
            linux/arm64
            linux/amd64
          build-args: |
            CACHE_EXCHANGE_RATES_PERIOD=
            DISABLE_READ_API=false
            API_PATH=/
            NETWORK_PATH=/
            DISABLE_WEBAPP=false
            DISABLE_WRITE_API=false
            CACHE_ENABLE_TOTAL_GAS_USAGE_COUNTER=
            WOBSERVER_ENABLED=false
            ADMIN_PANEL_ENABLED=
            CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL=
            SOCKET_ROOT=

  